[pytest]
addopts = 
    -v 
    --cov=prometheus_swarm 
    --cov-report=term-missing
    --cov-report=html:test-reports/coverage
    --cov-report=xml:test-reports/coverage.xml 
    --cov-config=.coveragerc
    --html=test-reports/report.html
testpaths = tests
python_files = test_*.py *_test.py
python_functions = test_*